version: "3.9"
services:
  mysqldb:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: contracts
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - internalnet
  nodeappone:
    container_name: nodeappcontainertwo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    env_file:
      - .env
    expose:
      - 3500
    networks:
      - internalnet
    depends_on:
      - mysqldb

networks:
  internalnet:
    driver: bridge
